// <auto-generated />
namespace tarea2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agregar_tabla_Cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregar_tabla_Cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "202010170159396_agregar_tabla_Cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
